// Regiunile României cu coordonatele centrului și zoom pentru hartă
export const ROMANIA_REGIONS = [
  { value: 'alba',         label: 'Alba',            lat: 46.08,  lng: 23.58,  zoom: 9 },
  { value: 'arad',         label: 'Arad',            lat: 46.17,  lng: 21.32,  zoom: 9 },
  { value: 'arges',        label: 'Argeș',           lat: 44.85,  lng: 24.87,  zoom: 9 },
  { value: 'bacau',        label: 'Bacău',           lat: 46.57,  lng: 26.91,  zoom: 9 },
  { value: 'bihor',        label: 'Bihor',           lat: 47.05,  lng: 22.00,  zoom: 9 },
  { value: 'bistrita',     label: 'Bistrița-Năsăud', lat: 47.13,  lng: 24.50,  zoom: 9 },
  { value: 'botosani',     label: 'Botoșani',        lat: 47.75,  lng: 26.67,  zoom: 9 },
  { value: 'brasov',       label: 'Brașov',          lat: 45.65,  lng: 25.61,  zoom: 9 },
  { value: 'braila',       label: 'Brăila',          lat: 45.27,  lng: 27.96,  zoom: 9 },
  { value: 'buzau',        label: 'Buzău',           lat: 45.15,  lng: 26.82,  zoom: 9 },
  { value: 'calarasi',     label: 'Călărași',        lat: 44.20,  lng: 27.33,  zoom: 9 },
  { value: 'caras',        label: 'Caraș-Severin',   lat: 45.30,  lng: 22.07,  zoom: 9 },
  { value: 'cluj',         label: 'Cluj',            lat: 46.77,  lng: 23.59,  zoom: 9 },
  { value: 'constanta',    label: 'Constanța',       lat: 44.18,  lng: 28.63,  zoom: 9 },
  { value: 'covasna',      label: 'Covasna',         lat: 45.85,  lng: 26.18,  zoom: 9 },
  { value: 'dambovita',    label: 'Dâmbovița',       lat: 44.93,  lng: 25.45,  zoom: 9 },
  { value: 'dolj',         label: 'Dolj',            lat: 44.33,  lng: 23.80,  zoom: 9 },
  { value: 'galati',       label: 'Galați',          lat: 45.43,  lng: 28.05,  zoom: 9 },
  { value: 'giurgiu',      label: 'Giurgiu',         lat: 43.90,  lng: 25.97,  zoom: 9 },
  { value: 'gorj',         label: 'Gorj',            lat: 44.95,  lng: 23.28,  zoom: 9 },
  { value: 'harghita',     label: 'Harghita',        lat: 46.43,  lng: 25.62,  zoom: 9 },
  { value: 'hunedoara',    label: 'Hunedoara',       lat: 45.72,  lng: 22.90,  zoom: 9 },
  { value: 'ialomita',     label: 'Ialomița',        lat: 44.60,  lng: 27.38,  zoom: 9 },
  { value: 'iasi',         label: 'Iași',            lat: 47.16,  lng: 27.59,  zoom: 9 },
  { value: 'ilfov',        label: 'Ilfov',           lat: 44.55,  lng: 26.10,  zoom: 9 },
  { value: 'maramures',    label: 'Maramureș',       lat: 47.66,  lng: 24.10,  zoom: 9 },
  { value: 'mehedinti',    label: 'Mehedinți',       lat: 44.63,  lng: 22.65,  zoom: 9 },
  { value: 'mures',        label: 'Mureș',           lat: 46.55,  lng: 24.57,  zoom: 9 },
  { value: 'neamt',        label: 'Neamț',           lat: 46.93,  lng: 26.37,  zoom: 9 },
  { value: 'olt',          label: 'Olt',             lat: 44.43,  lng: 24.38,  zoom: 9 },
  { value: 'prahova',      label: 'Prahova',         lat: 45.07,  lng: 25.98,  zoom: 9 },
  { value: 'salaj',        label: 'Sălaj',           lat: 47.19,  lng: 23.06,  zoom: 9 },
  { value: 'satu_mare',    label: 'Satu Mare',       lat: 47.80,  lng: 22.88,  zoom: 9 },
  { value: 'sibiu',        label: 'Sibiu',           lat: 45.80,  lng: 24.15,  zoom: 9 },
  { value: 'suceava',      label: 'Suceava',         lat: 47.65,  lng: 25.60,  zoom: 9 },
  { value: 'teleorman',    label: 'Teleorman',       lat: 44.02,  lng: 25.00,  zoom: 9 },
  { value: 'timis',        label: 'Timiș',           lat: 45.75,  lng: 21.22,  zoom: 9 },
  { value: 'tulcea',       label: 'Tulcea',          lat: 45.18,  lng: 28.80,  zoom: 9 },
  { value: 'valcea',       label: 'Vâlcea',          lat: 45.10,  lng: 24.37,  zoom: 9 },
  { value: 'vaslui',       label: 'Vaslui',          lat: 46.64,  lng: 27.73,  zoom: 9 },
  { value: 'vrancea',      label: 'Vrancea',         lat: 45.70,  lng: 26.98,  zoom: 9 },
  { value: 'bucuresti',    label: 'București',       lat: 44.43,  lng: 26.10,  zoom: 11 },
]